#!/usr/bin/env bash

# Quick test script for BorgWarehouse local development
# Only works in tests/docker/dev directory
# Never use in production!

set -e

# Working directory is tests/docker/dev
WORKDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VOLUMES_DIR="${WORKDIR}/volumes"
LOCAL_ENV="${WORKDIR}/.env"

echo "BorgWarehouse - Quick Test Script"
echo "Working in: ${WORKDIR}"
echo ""

# Create volumes directory (ONLY in tests/docker/dev/volumes)
mkdir -p "${VOLUMES_DIR}/config" "${VOLUMES_DIR}/ssh" "${VOLUMES_DIR}/ssh_host" "${VOLUMES_DIR}/repos"

# Set ownership to 1001:1001 (container user for testing)
# Note: If volumes already exist with correct ownership, this might fail - that's OK
echo "🔐 Setting permissions on volumes..."
sudo chown -R 1001:1001 "${VOLUMES_DIR}" 2>/dev/null || echo "Note: Ownership already correct or needs manual fix"
chmod -R 755 "${VOLUMES_DIR}" 2>/dev/null || true

# Check if local .env exists, if not create one
if [ ! -f "${LOCAL_ENV}" ]; then
    echo "📝 Creating local .env for testing..."
    
    NEXTAUTH_SECRET=$(openssl rand -hex 32)
    
    cat > "${LOCAL_ENV}" << EOF
# Quick test configuration - DO NOT USE IN PRODUCTION
# Auto-generated by docker-dev-start.sh
UID=1001
GID=1001
WEB_SERVER_PORT=3000
SSH_SERVER_PORT=2222
FQDN=localhost
CONFIG_PATH=${VOLUMES_DIR}/config
SSH_PATH=${VOLUMES_DIR}/ssh
SSH_HOST=${VOLUMES_DIR}/ssh_host
BORG_REPOSITORY_PATH=${VOLUMES_DIR}/repos
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=http://localhost:3000
NEXT_PUBLIC_APPNAME=BorgWarehouse
NEXT_PUBLIC_APPURL=http://localhost:3000
EOF
    echo "✅ .env created"
else
    echo "✅ Using existing .env"
fi

echo ""
echo "🔨 Building Docker image..."
cd "${WORKDIR}/../../../"  # Go to project root for docker compose
docker compose --env-file "${LOCAL_ENV}" -f docker-compose.yml -f "${WORKDIR}/docker-compose.override.yml" build

echo ""
echo "Starting BorgWarehouse..."
echo ""
echo "Access points:"
echo "   Web UI:  http://localhost:3000"
echo "   SSH:     ssh -p 2222 user@localhost"
echo ""
echo "Volumes: ${VOLUMES_DIR}"
echo "Env: ${LOCAL_ENV}"
echo ""
echo "Logs will appear below. Press Ctrl+C to stop."
echo ""

docker compose --env-file "${LOCAL_ENV}" -f docker-compose.yml -f "${WORKDIR}/docker-compose.override.yml" up
