# Run test against shells with "pre-commit run shellcheck --all-files"
repos:
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: shellcheck
            files: helpers/shells/
