version: '3'
services:
    borgwarehouse:
        container_name: borgwarehouse
        # If you want to build the image yourself, uncomment the following lines and comment the image line
        #build:
        #   context: .
        #   dockerfile: Dockerfile
        image: borgwarehouse/borgwarehouse
        user: "${UID:?UID variable missing}:${GID:?GID variable missing}"
        ports:
            - "${WEB_SERVER_PORT:?WEB_SERVER_PORT variable missing}:3000"
            - "${SSH_SERVER_PORT:?SSH_SERVER_PORT variable missing}:22"
        environment:
            - NEXTAUTH_URL=${NEXTAUTH_URL:?NEXTAUTH_URL variable missing}
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:?NEXTAUTH_SECRET variable missing}
            - CRONJOB_KEY=${CRONJOB_KEY:?CRONJOB_KEY variable missing}
            - SSH_SERVER_PORT=${SSH_SERVER_PORT:?SSH_SERVER_PORT variable missing}
            - FQDN=${FQDN:?FQDN variable missing}
        volumes:
            - ${CONFIG_PATH:?CONFIG_PATH variable missing}:/home/borgwarehouse/app/config
            - ${SSH_PATH:?SSH_PATH variable missing}:/home/borgwarehouse/.ssh
            - ${SSH_HOST:?SSH_HOST variable missing}:/etc/ssh
            - ${BORG_REPOSITORY_PATH:?BORG_REPOSITORY_PATH variable missing}:/home/borgwarehouse/repos
    
    # Apprise is used to send notifications, it's optional. http://apprise:8000 is the URL to use in BorgWarehouse.
    apprise:
        container_name: apprise
        image: caronc/apprise
        user: 'www-data:www-data'
