version: '3'
services:
    borgwarehouse:
        container_name: borgwarehouse
        # If you want to build the image yourself, uncomment the following lines and comment the image line
        #build:
        #   context: .
        #   dockerfile: Dockerfile
        #   args:
        #       - UID=${UID}
        #       - GID=${GID}
        image: borgwarehouse/borgwarehouse
        user: '${UID:?UID variable missing}:${GID:?GID variable missing}'
        ports:
            - '${WEB_SERVER_PORT:?WEB_SERVER_PORT variable missing}:3000'
            - '${SSH_SERVER_PORT:?SSH_SERVER_PORT variable missing}:22'
        env_file:
            - .env
        volumes:
            - ${CONFIG_PATH:?CONFIG_PATH variable missing}:/home/borgwarehouse/app/config
            - ${SSH_PATH:?SSH_PATH variable missing}:/home/borgwarehouse/.ssh
            - ${SSH_HOST:?SSH_HOST variable missing}:/etc/ssh
            - ${BORG_REPOSITORY_PATH:?BORG_REPOSITORY_PATH variable missing}:/home/borgwarehouse/repos
            - ${TMP_PATH:?TMP_PATH variable missing}:/home/borgwarehouse/tmp
            - ${LOGS_PATH:?LOGS_PATH variable missing}:/home/borgwarehouse/logs
    # Apprise is used to send notifications, it's optional. http://apprise:8000 is the URL to use in BorgWarehouse.
    apprise:
        container_name: apprise
        image: caronc/apprise
        user: 'www-data:www-data'
