// Auto-curated registry: maps a repo icon name to its Tabler component.
// Named imports keep tree-shaking effective (only these icons are bundled).
import { createElement } from 'react';
import type { Icon, IconProps } from '@tabler/icons-react';
import {
  IconGhost2,
  IconGhost,
  IconDatabase,
  IconDatabaseCog,
  IconDatabaseImport,
  IconDatabaseExport,
  IconServer,
  IconServer2,
  IconServerBolt,
  IconServerCog,
  IconDeviceFloppy,
  IconDeviceSdCard,
  IconDisc,
  IconBuildingWarehouse,
  IconCloud,
  IconCloudUpload,
  IconCloudCheck,
  IconCloudLock,
  IconWorld,
  IconWorldUpload,
  IconNetwork,
  IconRouter,
  IconPlug,
  IconUsb,
  IconArchive,
  IconBox,
  IconPackage,
  IconPackages,
  IconStack,
  IconStack2,
  IconFolder,
  IconFolderOpen,
  IconFiles,
  IconFileZip,
  IconHistory,
  IconRefresh,
  IconDeviceDesktop,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDeviceTv,
  IconDevices,
  IconCpu,
  IconLock,
  IconLockCheck,
  IconShield,
  IconShieldCheck,
  IconShieldLock,
  IconKey,
  IconFingerprint,
  IconBrandWindows,
  IconBrandApple,
  IconBrandUbuntu,
  IconBrandDebian,
  IconBrandRedhat,
  IconBrandAndroid,
  IconBrandDocker,
  IconPhoto,
  IconVideo,
  IconMusic,
  IconMail,
  IconCode,
  IconTerminal,
  IconHome,
  IconBuilding,
  IconBuildingBank,
  IconBriefcase,
  IconClock,
  IconCalendarTime,
  IconChartBar,
  IconChartLine,
  IconHexagon,
  IconCircleDot,
} from '@tabler/icons-react';
import { DEFAULT_REPO_ICON, BORGWAREHOUSE_ICON } from './repoIcons';
import BorgWarehouseIcon from './BorgWarehouseIcon';

const ICON_MAP: Record<string, Icon> = {
  IconGhost2,
  IconGhost,
  IconDatabase,
  IconDatabaseCog,
  IconDatabaseImport,
  IconDatabaseExport,
  IconServer,
  IconServer2,
  IconServerBolt,
  IconServerCog,
  IconDeviceFloppy,
  IconDeviceSdCard,
  IconDisc,
  IconBuildingWarehouse,
  IconCloud,
  IconCloudUpload,
  IconCloudCheck,
  IconCloudLock,
  IconWorld,
  IconWorldUpload,
  IconNetwork,
  IconRouter,
  IconPlug,
  IconUsb,
  IconArchive,
  IconBox,
  IconPackage,
  IconPackages,
  IconStack,
  IconStack2,
  IconFolder,
  IconFolderOpen,
  IconFiles,
  IconFileZip,
  IconHistory,
  IconRefresh,
  IconDeviceDesktop,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDeviceTv,
  IconDevices,
  IconCpu,
  IconLock,
  IconLockCheck,
  IconShield,
  IconShieldCheck,
  IconShieldLock,
  IconKey,
  IconFingerprint,
  IconBrandWindows,
  IconBrandApple,
  IconBrandUbuntu,
  IconBrandDebian,
  IconBrandRedhat,
  IconBrandAndroid,
  IconBrandDocker,
  IconPhoto,
  IconVideo,
  IconMusic,
  IconMail,
  IconCode,
  IconTerminal,
  IconHome,
  IconBuilding,
  IconBuildingBank,
  IconBriefcase,
  IconClock,
  IconCalendarTime,
  IconChartBar,
  IconChartLine,
  IconHexagon,
  IconCircleDot,
};

export const getRepoIconComponent = (name?: string): Icon =>
  (name && ICON_MAP[name]) || ICON_MAP[DEFAULT_REPO_ICON] || ICON_MAP.IconGhost2;

type RepoIconProps = IconProps & { name?: string };

export default function RepoIcon({ name, ...props }: RepoIconProps) {
  const resolved =
    name && (ICON_MAP[name] || name === BORGWAREHOUSE_ICON) ? name : DEFAULT_REPO_ICON;
  if (resolved === BORGWAREHOUSE_ICON) {
    return <BorgWarehouseIcon size={props.size} color={props.color} className={props.className} />;
  }
  return createElement(ICON_MAP[resolved], props);
}
