name: Build and Push Docker Image for Develop Branch

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Update package.json version
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          echo "Current Commit: $COMMIT"
          jq '.version = "develop-'$COMMIT'"' package.json > package.tmp.json
          mv package.tmp.json package.json
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64 # linux/arm/v7 arm32 is not supported by node20 https://github.com/nodejs/docker-node/issues/1946
          tags: borgwarehouse/borgwarehouse:develop
